export const SONGS_INTRO =
  'The utterances of Bhakti, Sufi and Baul poets have been kept alive over centuries through song, and that is what you find here - live recordings of oral poetry all the way from Pakistan in the west to Bengal in the east, pulsating to rhythm and melody, sung and recorded in contexts as diverse as urban stages and village squares, on trains and road journeys, in living rooms and under the wide open sky.';

export const SONGS_FILTER = [
  'All',
  ...Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i)),
];

export const MOCK_SONGS = [
  {
    id: 1,
    Songtitle_transliteration: 'Aarshi Nogor',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Baul, Lalon Fakir, Mysticism',
  },
  {
    id: 2,
    Songtitle_transliteration: 'Ab Thaara Laal Samandada Ra',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Bhakti, Kabir, Love',
  },
  {
    id: 3,
    Songtitle_transliteration: 'Aarshi Nogor',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Sufi, Bulleh Shah, Peace',
  },
  {
    id: 4,
    Songtitle_transliteration: 'Ab Thaara Laal Samandada Ra',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Bhakti, Mirabai, Devotion',
  },
  {
    id: 5,
    Songtitle_transliteration: 'Aarshi Nogor',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Baul, Lalon Fakir, Mysticism',
  },
  {
    id: 6,
    Songtitle_transliteration: 'Ab Thaara Laal Samandada Ra',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Bhakti, Kabir, Love',
  },
  {
    id: 7,
    Songtitle_transliteration: 'Aarshi Nogor',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Sufi, Bulleh Shah, Peace',
  },
  {
    id: 8,
    Songtitle_transliteration: 'Ab Thaara Laal Samandada Ra',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Bhakti, Mirabai, Devotion',
  },
  {
    id: 9,
    Songtitle_transliteration: 'Aarshi Nogor',
    songtitletraan: 'City Of Mirrors',
    singer: 'PARVATI BAUL',
    poet: 'LALON FAKIR',
    thumbnailUrl: '/placeholder.svg',
    meta_keywords: 'Baul, Mysticism, Peace',
  },
];
