'use client';

/**
 * CLNews — Ajab News page component
 *
 * ── API DATA vs GENERATED DATA ──────────────────────────────────────────────
 *
 * FROM THE API  (GET /Api/news — https://ajab.designanddevelopment.in/admin):
 *   Real content items (popup_items populated):
 *     id 28 → single: "Ajab Gazab Bazaar in Kutch" (no image in CMS yet)
 *              multiple: "Games and Activities at AGB 2026" (3 CMS images ✓)
 *     id 27 → same content as 28 (CMS duplicate — should be removed by CMS team)
 *
 *   Junk/test items (filtered out — no valid popup_items):
 *     ids 9–23 → empty popup_items[], test names ("rohit", "sdfasdfasdf")
 *     id 26    → test titles ("asd", "qwee")
 *     id 30    → title "test"
 *     id 29    → video only (category:"video" not yet handled)
 *
 * GENERATED BY US  (MOCK_NEWS — shown only when API returns no valid items):
 *   "Ajab Gazab Bazaar in Kutch" (single, no image)
 *   "Had Anhad | I Lost My Heart To Nizam's Glance" (single, no image)
 *   These are Figma placeholder texts, NOT real CMS content.
 *
 * LAYOUT (matches Figma node 1:18663):
 *   Section 1 (idx 0): Full-width image OR image-less title block
 *   Section 2 (idx 1): Full-width slider with left/right arrows
 *   Section 3 (idx 2): Thumbnail (280×156) on left, title + text on right
 *   Sections 4+       : Hidden behind "See more / See less" toggle
 * ────────────────────────────────────────────────────────────────────────────
 */

import React, { useEffect, useState } from 'react';
import './CLNews.css';
import { AJAB_API_BASE } from '@/lib/ajabEnv';
import { filterNewsForPublicSite } from '@/lib/cmsNews';
import { withAppBasePath } from '@/lib/resolveCmsAssetUrl';

type PopupCategory = 'single' | 'multiple';

interface ApiPopupItem {
  category?: string;
  title?: string;
  second_title?: string;
  content?: string;
  image?: string;
  images?: string[];
  published?: string | null;
  show_on_home?: string | null;
  // [Claude] these changes have been recommended by claude — optional caption field for image.
  image_caption?: string;
}

interface ApiNewsItem {
  id: string;
  news_title?: string | null;
  news_second_title?: string | null;
  ajab_news_content?: string | null;
  published?: string | null;
  popup_items?: ApiPopupItem[];
}

interface Section {
  id: string;
  title: string;
  secondTitle: string;
  content: string;
  category: PopupCategory;
  images: string[];
  showDivider: boolean;
  // [Claude] these changes have been recommended by claude — optional italic caption shown
  // directly under the image (matches PDF page 3 "The Kabir Project team with volunteers" line).
  imageCaption?: string;
}

const NEWS_ASSET_BASE = `${AJAB_API_BASE}/`;

// [Claude] these changes have been recommended by claude — news images not yet uploaded to CMS.
// The API currently returns junk/test CMS entries that push the real content to wrong section indices,
// breaking the slider at idx=1. We use static Figma-reference data so the layout matches PDF page 3
// exactly. Image URLs are real CMS assets from id=28 (the only valid news entry in the API).
// To re-enable the API, replace buildSections(FIGMA_NEWS) with the load() call below.

// [Claude] these changes have been recommended by claude — news images not yet uploaded to CMS.
// We crop the exact, high-resolution original images directly from the Home PDF page 3
// and reference them here. This ensures our local news page looks exactly like the design PDF.
const IMG_A = withAppBasePath('/news-assets/kabir-project-team.png');
const IMG_B = withAppBasePath('/news-assets/kabir-project-slider-1.png');
const IMG_C = withAppBasePath('/news-assets/had-anhad-thumbnail.png');

const FIGMA_NEWS: ApiNewsItem[] = [
  {
    // ── Article 1 ───────────────────────────────────────────────────────────────
    // popup_item 0  →  Section 0 (idx=0) — FullWidthSection: title above + single image + text below
    // popup_item 1  →  Section 1 (idx=1) — Slider: images with arrows + heading + text below (no title above)
    id: 'figma-1',
    popup_items: [
      {
        category: 'single',
        title: 'Gulshan-e-Armaan',
        second_title: 'KABIR PROJECT',
        image: IMG_A,
        image_caption: 'The Kabir Project team with volunteers',
        content:
          'The story highlights the gulshan-e-na-afreeda (the Uncreated Garden) that Shah Inayat spoke of, to evoke his utopian vision of a world in which the human spirit was not driven by fear, mistrust, oppression and exploitation, but rather was guided by a non-egoic spirit of connection and love. The story highlights the gulshan-e-na-afreeda (the Uncreated Garden) that Shah Inayat spoke of, to evoke his utopian vision of a world in which the human spirit was not driven by fear, mistrust, oppression and exploitation, but rather was guided by a non-egoic spirit of connection and love.',
      },
      {
        category: 'multiple',
        title: 'Haman Hai Ishq',
        second_title: '',
        images: [IMG_B, IMG_B, IMG_B],
        content:
          'The story highlights the gulshan-e-na-afreeda (the Uncreated Garden) that Shah Inayat spoke of, to evoke his utopian vision of a world in which the human spirit was not driven by fear, mist. The story highlights the gulshan-e-na-afreeda (the Uncreated Garden) that Shah Inayat spoke of, to evoke his utopian vision of a world in which the human spirit was not driven by fear, mistrust Shah Inayat spoke of, to evoke his utopian vision of a world.',
      },
    ],
  },
  {
    // ── Article 2 ───────────────────────────────────────────────────────────────
    // popup_item 0  →  Section 2 (idx=2) — ThumbnailSection: small image left + title + text right
    id: 'figma-2',
    popup_items: [
      {
        category: 'single',
        title: 'Had Anhad',
        second_title: "I Lost My Heart To Nizam's Glance",
        image: IMG_C,
        content:
          'The story highlights the gulshan-e-na-afreeda (the Uncreated Garden) that Shah Inayat spoke of, to evoke his utopian vision of a world in which the human spirit was not driven by fear, mistrust, oppression and exploitation, but rather was guided by a non-egoic spirit of connection and love.',
      },
    ],
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────

const stripHtml = (v?: string | null) =>
  v ? v.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim() : '';

const toImageUrl = (v?: string) => {
  if (!v) return '';
  if (v.startsWith('http://') || v.startsWith('https://')) return v;
  if (v.startsWith('/')) return withAppBasePath(v);
  return `${NEWS_ASSET_BASE}${v.replace(/^\/+/, '')}`;
};

/** Determine if secondTitle is a subtitle phrase vs a byline name.
 *  Subtitles start with a capital "I " or contain mixed case with spaces.
 *  Bylines are typically short ALL-CAPS or proper-name strings. */
const isSubtitlePhrase = (s: string) =>
  s.startsWith('I ') ||
  (s.includes(' ') && s !== s.toUpperCase() && s.length > 20);

// ─── ToggleText ───────────────────────────────────────────────────────────────
function ToggleText({ text }: { text: string }) {
  const [expanded, setExpanded] = useState(false);
  const truncateLimit = 520;
  const isLong = text.length > truncateLimit + 20;

  if (!isLong) {
    return (
      <div className="news-text-wrap">
        <p className="leading-relaxed news-line-content">
          {text}
        </p>
      </div>
    );
  }

  const truncated = text.slice(0, truncateLimit).trim();

  return (
    <div className="news-text-wrap">
      <p className="leading-relaxed news-line-content">
        {expanded ? text : truncated}
        <span
          onClick={() => setExpanded(!expanded)}
          className="pink-text cursor-pointer hover:underline inline-block"
          style={{ marginLeft: '6px', whiteSpace: 'nowrap' }}
        >
          {expanded ? ' See less' : ' ...more'}
        </span>
      </p>
    </div>
  );
}

// ─── ImageSlider (used for section 2 — multiple images with arrows) ───────────
function ImageSlider({ images }: { images: string[] }) {
  const [idx, setIdx] = useState(0);
  if (!images.length) return null;
  const prev = () => setIdx((i) => (i - 1 + images.length) % images.length);
  const next = () => setIdx((i) => (i + 1) % images.length);

  return (
    <div className="news-card-slider-row">
      <div className="news-banner-shadow news-image-wrap">
        <img src={images[idx]} alt="News image" loading="eager" decoding="async" />
      </div>
      {images.length > 1 && (
        <>
          <button onClick={prev} className="news-slider-prev" aria-label="Previous">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="51" viewBox="0 0 26 51" fill="none">
              <path d="M22.8301 0.359375C22.1201 0.619375 21.6001 1.16939 21.0901 1.74939C14.6701 8.90939 8.2401 16.0694 1.8101 23.2294C0.910101 24.2294 0.720112 25.3994 1.29011 26.4794C1.42011 26.7294 1.6001 26.9494 1.7801 27.1594C8.3601 34.4894 14.9401 41.8194 21.5301 49.1494C22.7801 50.5394 24.6001 50.2894 25.3101 48.6194C25.6801 47.7394 25.6001 46.8894 25.1001 46.0994C24.9601 45.8794 24.7801 45.6794 24.6101 45.4894C18.6801 38.8794 12.7401 32.2694 6.80009 25.6594C6.68009 25.5294 6.5101 25.4393 6.3701 25.3293C6.3701 25.2593 6.3701 25.1794 6.3701 25.1094C6.5101 24.9994 6.68009 24.9094 6.80009 24.7794C12.7701 18.1394 18.7301 11.4994 24.7001 4.84937C25.6101 3.82937 25.7901 2.63945 25.1901 1.55945C24.8501 0.929448 24.3001 0.619385 23.7101 0.369385H22.8401L22.8301 0.359375Z" fill="#B3B3B3"/>
            </svg>
          </button>
          <button onClick={next} className="news-slider-next" aria-label="Next">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="51" viewBox="0 0 26 51" fill="none">
              <path d="M3.21029 0.359375C3.92029 0.619375 4.44028 1.16939 4.95028 1.74939C11.3703 8.90939 17.8003 16.0694 24.2303 23.2294C25.1303 24.2294 25.3203 25.3994 24.7503 26.4794C24.6203 26.7294 24.4403 26.9494 24.2603 27.1594C17.6803 34.4894 11.1003 41.8194 4.51034 49.1494C3.26034 50.5394 1.44031 50.2894 0.73031 48.6194C0.36031 47.7394 0.440271 46.8894 0.940271 46.0994C1.08027 45.8794 1.26038 45.6794 1.43038 45.4894C7.36038 38.8794 13.3003 32.2694 19.2403 25.6594C19.3603 25.5294 19.5304 25.4393 19.6704 25.3293C19.6704 25.2593 19.6704 25.1794 19.6704 25.1094C19.5304 24.9994 19.3603 24.9094 19.2403 24.7794C13.2703 18.1394 7.3103 11.4994 1.3403 4.84937C0.430295 3.82937 0.250305 2.63945 0.850305 1.55945C1.19031 0.929448 1.74029 0.619385 2.33029 0.369385H3.20028L3.21029 0.359375Z" fill="#B3B3B3"/>
            </svg>
          </button>
        </>
      )}
    </div>
  );
}

// ─── Section renderers ────────────────────────────────────────────────────────

/** Section 1 & 2: Full-width image with title above, heading + text below
 *  [Claude] these changes have been recommended by claude — when useSlider is true (idx=1),
 *  the section renders as a pure image carousel only (no title above, no text below).
 *  This matches PDF page 3 (Figma node 1:18663) where the second section is an image-only
 *  slider with ← → arrows and no accompanying title or body text. */
function FullWidthSection({ section, useSlider }: { section: Section; useSlider: boolean }) {
  const isSubtitle = isSubtitlePhrase(section.secondTitle);
  const hasImage = section.images.length > 0;

  // [Claude] these changes have been recommended by claude — slider section (idx=1) shows:
  // images with arrows (NO title above), then heading + text below.
  // Matches PDF page 3: the slider flows directly into its description without a title label above.
  if (useSlider) {
    return (
      <>
        <ImageSlider images={section.images} />
        <div className="news-detals-row">
          <h2 className="custom-heading-font">
            {section.title}
            {!!section.secondTitle && isSubtitle && (
              <span className="news-subtitle-italic"> {section.secondTitle}</span>
            )}
          </h2>
          {!!section.content ? (
            <ToggleText text={section.content} />
          ) : (
            <p className="leading-relaxed">No content available.</p>
          )}
        </div>
      </>
    );
  }

  return (
    <>
      {/* Title ABOVE image (Figma: "Gulshan-e-Armaan by KABIR PROJECT") */}
      {hasImage && (
        <div className="news-above-title-row">
          <p style={{ margin: 0, lineHeight: 1.3 }}>
            <span className="news-above-main-title">{section.title}</span>
            {!!section.secondTitle && !isSubtitle && (
              <>
                <span className="news-above-by-label"> by </span>
                <span className="news-above-by-value">{section.secondTitle}</span>
              </>
            )}
            {!!section.secondTitle && isSubtitle && (
              <span className="news-subtitle-italic"> {section.secondTitle}</span>
            )}
          </p>
        </div>
      )}

      {/* Single image */}
      {hasImage && (
        <div className="news-card-slider-row">
          <div className="news-banner-shadow news-image-wrap">
            <img src={section.images[0]} alt={section.title} loading="eager" decoding="async" />
          </div>
        </div>
      )}

      {/* [Claude] these changes have been recommended by claude — italic caption directly under
          the image (PDF page 3 shows "The Kabir Project team with volunteers" here). */}
      {hasImage && !!section.imageCaption && (
        <p className="news-image-caption">{section.imageCaption}</p>
      )}

      {/* Heading + body text below image */}
      <div className="news-detals-row">
        <h2 className="custom-heading-font">
          {section.title}
          {!!section.secondTitle && isSubtitle && (
            <span className="news-subtitle-italic"> {section.secondTitle}</span>
          )}
        </h2>
        {!!section.content ? (
          <ToggleText text={section.content} />
        ) : (
          <p className="leading-relaxed">No content available.</p>
        )}
      </div>
    </>
  );
}

/** Section 3+: Thumbnail (280×156) on left, title + text on right */
function ThumbnailSection({ section }: { section: Section }) {
  const isSubtitle = isSubtitlePhrase(section.secondTitle);
  const hasImage = section.images.length > 0;

  return (
    <div className="news-thumb-row">
      {hasImage && (
        <div className="news-thumb-img">
          <img src={section.images[0]} alt={section.title} loading="eager" decoding="async" />
        </div>
      )}
      <div className={`news-thumb-content${!hasImage ? ' w-full' : ''}`}>
        <h2 className="news-thumb-heading">
          {section.title}
          {!!section.secondTitle && isSubtitle && (
            <span className="news-subtitle-italic"> {section.secondTitle}</span>
          )}
          {!!section.secondTitle && !isSubtitle && (
            <>
              {' '}
              <span className="news-above-by-label">by </span>
              <span className="news-above-by-value">{section.secondTitle}</span>
            </>
          )}
        </h2>
        {!!section.content ? (
          <ToggleText text={section.content} />
        ) : (
          <p className="leading-relaxed">No content available.</p>
        )}
      </div>
    </div>
  );
}

// ─── Main Component ────────────────────────────────────────────────────────────
export default function CLAjabnews() {
  const [sections, setSections] = useState<Section[]>(() => buildSections(FIGMA_NEWS));
  const [showAll, setShowAll] = useState(false);

  useEffect(() => {
    const load = async () => {
      try {
        const res = await fetch(`${AJAB_API_BASE}/Api/news`, { cache: 'no-store' });
        if (!res.ok) return;
        const json = await res.json();
        const raw: ApiNewsItem[] = Array.isArray(json?.data) ? json.data : [];
        const built = buildSections(raw);
        if (built.length) setSections(built);
      } catch {
        /* FIGMA_NEWS fallback already in state */
      }
    };
    void load();
  }, []);

  /** How many sections to show before "See more" button */
  const VISIBLE_COUNT = 3;

  if (!sections.length)
    return (
      <div className="custom-inner-container mx-auto" style={{ paddingTop: 40, color: '#6d6e71' }}>
        No Ajab News found.
      </div>
    );

  const visibleSections = showAll ? sections : sections.slice(0, VISIBLE_COUNT);
  const hasMore = sections.length > VISIBLE_COUNT;

  return (
    <div className="custom-inner-container mx-auto">
      {visibleSections.map((section, idx) => {
        // Section 0: single full-width image
        // Section 1: slider (multiple images with arrows)
        // Section 2+: thumbnail layout
        const useSlider = idx === 1 && section.images.length > 1;
        const useThumbnail = idx >= 2;

        return (
          <article key={section.id}>
            {useThumbnail ? (
              <ThumbnailSection section={section} />
            ) : (
              <FullWidthSection section={section} useSlider={useSlider} />
            )}

            {/* Dotted separator between articles */}
            {section.showDivider && idx < visibleSections.length - 1 && (
              <div className="border-dotted-seprator" />
            )}
            {/* Separator at the end of the last visible item if more are hidden */}
            {idx === visibleSections.length - 1 && hasMore && !showAll && section.showDivider && (
              <div className="border-dotted-seprator" />
            )}
          </article>
        );
      })}

      {/* See more / See less */}
      {hasMore && (
        <div className="news-see-more-wrap">
          <button
            type="button"
            className="news-see-more-btn"
            onClick={() => setShowAll((v) => !v)}
          >
            {showAll ? 'SEE LESS' : 'SEE MORE'}
          </button>
        </div>
      )}
    </div>
  );
}

// ─── Helper: flatten news items → sections ────────────────────────────────────
function buildSections(raw: ApiNewsItem[]): Section[] {
  const items = filterNewsForPublicSite(raw);

  const all: Section[] = items.flatMap((news) => {
    const pops = (news.popup_items || []).filter(
      (p) => p?.category === 'single' || p?.category === 'multiple'
    );

    return pops.map((p, pi) => {
      const images =
        p.category === 'single'
          ? [toImageUrl(p.image)].filter(Boolean)
          : Array.isArray(p.images)
          ? p.images.map((e) => toImageUrl(e)).filter(Boolean)
          : [];

      return {
        id: `${news.id}-${pi}`,
        title: p.title || news.news_title || 'Untitled',
        secondTitle: p.second_title || news.news_second_title || '',
        content: p.content || stripHtml(news.ajab_news_content) || '',
        category: p.category as PopupCategory,
        images,
        showDivider: true, // always true; rendering logic controls visibility
        imageCaption: p.image_caption || '',
      };
    });
  });

  return all;
}
